import type { Metadata } from "next";
import React from "react";
import { Box } from "@chakra-ui/react";
import { Provider } from "@/components/ui/provider"; // Chakra UI Provider
import Sidebar from "@/components/otros/sidebar"; // Asegúrate de tener tu Sidebar exportado correctamente

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout(props: { children: React.ReactNode }) {
  const { children } = props
  return (
    <html suppressHydrationWarning>
      <body>
        <Provider>
           <Box display="flex" minH="100vh">
             <Sidebar userRole={'admin'}  />
               {children}
          </Box>
         </Provider>
      </body>
    </html>
  )
}

