import type { Metadata } from "next";
import React from "react";
import { Box } from "@chakra-ui/react";
import { Provider } from "@/components/ui/provider"; // Chakra UI Provider
import Sidebar from "@/components/otros/sidebar"; // Asegúrate de tener tu Sidebar exportado correctamente

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html suppressHydrationWarning>
      <body className={`flex antialiased`}>
        <Provider>
          
            <Sidebar userRole={'admin'} />
            <Box flex="1" ml={{ base: 0, md: '250px' }} p={4}>
              {children}
            </Box>
          
        </Provider>
      </body>
    </html>
  );
}
